CREATE TABLE Customer (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Active BIT NOT NULL,
    CreatedAt DATETIME NOT NULL,
    Name NVARCHAR(255) NOT NULL,
    MonthlyBudget INT NOT NULL
);

CREATE TABLE Developer (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Active BIT NOT NULL,
    CreatedAt DATETIME NOT NULL,
    Name NVARCHAR(255) NOT NULL,
    Role NVARCHAR(255) NOT NULL,
    CostPerHour INT NOT NULL
);

CREATE TABLE Activity (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Active BIT NOT NULL,
    CreatedAt DATETIME NOT NULL,
    IdDeveloper UNIQUEIDENTIFIER NOT NULL,
    IdCustomer UNIQUEIDENTIFIER NOT NULL,
    Hours FLOAT NOT NULL,
    FOREIGN KEY (IdDeveloper) REFERENCES Developer(Id),
    FOREIGN KEY (IdCustomer) REFERENCES Customer(Id)
);